version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - path: ./back/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  # server:
  #   build: .
  #   command: npm run start:dev
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  #     NODE_ENV: development
